#my_string = input('Введите Ваше имя: ')
#print('В вашем имени',len(my_string),'букв')
my_string = input('Введите произвольное предлдожение ')
#print(my_string)
#print(my_string.upper())
#print(my_string. lower())
#print(my_string. replace(' ', '#'))
#print(my_string[0])
print(my_string[-1])